apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: dockerhub-terasky
  namespace: flux-system
spec:
  type: dockerhub
  secretRef:
    name: webhook-token
  resources:
    - kind: ImageRepository
      name: imagerepository
---

apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: image-update
  namespace: flux-system
spec:
  interval: 2m
  sourceRef:
    kind: GitRepository
    name: git-repo-flux
  git:
    checkout:
      ref:
        branch: terasky
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: terasky
  update:
    path: ./clusters/my-cluster/flux-system
    strategy: Setters
