apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: hello-terasky2
  namespace: default
spec:
  tag: dsahar/terasky:0.0.3
  serviceAccountName: service-account
  build:
  builder:
    name: my-builder
    kind: Builder
  source:
    git:
      url: https://github.com/danielsahar15/terasky.git
      revision: terasky
