apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: petclinic-release-chartmuseum
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: hello
      version: '0.1.0'
      sourceRef:
        kind: HelmRepository
        name: chartmuseum
        namespace: flux-system
      interval: 1m
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
    image:
      repository: docker.io/dsahar/terasky-petclinic # {"$imagepolicy": "flux-system:imagepolicy:name"}
      tag: 0.0.4 # {"$imagepolicy": "flux-system:imagepolicy:tag"}
    replicaCount: 1
