apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name:  petclinic-release
  namespace: default
spec:
  interval: 5m
  releaseName: petclinic-release
  upgrade:
    remediation:
      remediateLastFailure: true
  chart:
    spec:
      chart: hello
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: chartmuseum
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository:  dsahar/terasky
      tag: 0.0.3 # {"$imagepolicy": "flux-system:imagepolicy"}
    replicaCount: 1
~                    
