apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: petclinic-release
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ../../../Helm/Chart.yaml
      sourceRef:
        kind: GitRepository
        name: git-repo-flux
        namespace: flux-system
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: values
      valuesKey: values.yaml
