apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- HelmRelease.yaml
- image.yaml
- chartmuseum/HelmRepository.yaml
- chartmuseum/storage-class.yaml
- chartmuseum/namespace.yaml
- chartmuseum/persistent-volume.yaml
- chartmuseum/persistent-volume-claim.yaml
- git-charts-repo.yaml

