apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hello-release
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: hello
      version: '0.1.0'
      sourceRef:
        kind: HelmRepository
        name: chartmuseum
        namespace: flux-system
      interval: 1m
