apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hello-release-3
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: hello
      version: latest
      sourceRef:
        kind: HelmRepository
        name: chartmuseum
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository:  dsahar/terasky
      tag: latest
    replicaCount: 2
