
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: terasky
  namespace: default
spec:
  releaseName: terasky
  chart:
    repository: http://localhost:8081
    name: hello
    version: 0.1.0
  values:
    image:
      repository: dsahar/terasky
      tag: latest
